### PR TITLE
refactor: changes to get it running

### PR DESCRIPTION
**Pull request by chadoh**
* needed to update near-shell to get it to run with `yarn dev`
* add license to package.json to quiet warning (matches dual license
  used in other NEAR projects)
* running `yarn dev` resulted in changes to compiled wasm file; to me it
  seems like these binaries are build artifacts that should be
  gitignored, but it seems to be our custom to check them in, so that's
  what I've done here

### CODE REVIEW

**Comment by vgrichina** [comment]
@chadoh 

> running yarn dev resulted in changes to compiled wasm file; to me it
seems like these binaries are build artifacts that should be
gitignored, but it seems to be our custom to check them in, so that's
what I've done here

hmm, why our custom to check in them?

**Comment by mattlockyer** [comment]
@chadoh @vgrichina would we not want to recompile the contract to wasm with yarn dev?

What if someone is editing the contracts of this example?

Again, this is how create-near-app was configured to run.

**Comment by chadoh** [comment]
> custom to check in them

I think it _might_ make sense to check compiled wasm files into examples like `high-level-cross-contract`, to make it easier to walk through the README. However, that entire example should be reimagined and rebuilt in a more approachable way.

So if we are ok with changing our default to add wasm files to gitignore, I would strongly support that move. I've created https://github.com/near/devx/issues/205 to track this.

**Comment by vgrichina** [comment]
@chadoh 
> I think it might make sense to check compiled wasm files into examples like high-level-cross-contract, to make it easier to walk through the README. However, that entire example should be reimagined and rebuilt in a more approachable way.

I think it brings us back to question that we should have some build system for multiple contracts. Seems like most of these are committed when they are dependency of another contract?

**Comment by vgrichina** [comment]
@mattlockyer I think we for sure want to be recompiling contracts using `yarn dev`. There are currently 2 problems AFAIK:
1) In `create-near-app` contract is recompiled by `yarn dev` when you change source code. In examples it was broken for some reason cc @mikedotexe 
2) Multi-contracts setup doesn't have some universal way to build / deploy multiple contracts right now.

**Pull request merged**
